### ISSUE TITLE
Quelques retours sur votre code

### ISSUE THREAD

**Issue by nivetml** [antocreadev/Ateliers-L3SINF#1]
- Un peu dommage de partir sur une structure de donnée ou les bornes d'IMC sont répétées deux fois... Or la borne inférieure d'un intervalle est obligatoirement la borne supérieure de l'intervalle du dessus... Donc je pense que vous pouvez améliorer cela !
https://github.com/antocreadev/Ateliers-L3SINF/blob/dc11c3a93a33e21268fee56dd1115e46278374b0/1/calculImc.py#L17
- Définissez un peu votre jeu de test en définissant ce qu'il représente, à minima il faudrait dire ce que représente les trois composant de vos triplet...
https://github.com/antocreadev/Ateliers-L3SINF/blob/262da95f3808ba37018373fff0fd674ecdcc4b70/1/equationSecondDegre.py#L2
- Vous devriez spécifier que la variable num ne peut prendre que deux valeurs différentes...
https://github.com/antocreadev/Ateliers-L3SINF/blob/262da95f3808ba37018373fff0fd674ecdcc4b70/1/equationSecondDegre.py#L45C7-L45C7
- Je préfèrerais un seul return pour toute la fonction et l'utilisation d'une variable result valuée à chaque fois
https://github.com/antocreadev/Ateliers-L3SINF/blob/262da95f3808ba37018373fff0fd674ecdcc4b70/1/equationSecondDegre.py#L69
- Pour aller jusqu'au bout de la logique de test il faut définir les valeurs de résultats attendus également... Là, en l'état il est difficile de savoir si votre code fonctionne ou pas !!! Normalement un test c'est un couple (input, output souhaitée) et si l'output souhaitée est celle obtenu alors le test est considéré comme passé !!!
https://github.com/antocreadev/Ateliers-L3SINF/blob/262da95f3808ba37018373fff0fd674ecdcc4b70/1/equationSecondDegre.py#L102

**Comment by antocreadev** [comment]
Merci pour vos retours, 
Les modifications ont été faites. 
Plus précisément, dans le fichier ```calculImc.py```, j'ai changé la structure de donnée afin de garder seulement les bornes supérieurs et j'ai changé ma boucle passant à une boucle while avec une condition d'arrêt correspondant aux bornes.
Ensuite, dans le fichier ```equationSecondDegre.py```,  j'ai expliqué la structure de ma liste pour le test et ajouter l'output attendu, et modifier ma fonction test() pour intégré l'ouput attendu avec celui de la fonction qu'on test. Puis, dans ce même fichier j'ai supprimer les ```return``` dans la fonction ```solution_equation```pour en garder qu'un seul et ajouter une condition gérer l'erreur lorsque ```a``` est différent de 0.
